---
- name: Setup homelab
  hosts:
    - server

  tasks:
    - name: Validate sudo pass has been set as env var
      ansible.builtin.assert:
        that: lookup('ansible.builtin.env', 'ANSIBLE_BECOME_PASS') != ''
        fail_msg: "Env var ANSIBLE_BECOME_PASS is not set, cannot continue!"
      tags:
        - always

    - name: Setup filesystem (btrfs)
      ansible.builtin.include_role:
        name: filesystem
      tags:
        - filesystem

    - name: Install packages
      ansible.builtin.include_role:
        name: common
      tags:
        - common

    - name: Setup networking
      ansible.builtin.include_role:
        name: networking
      tags:
        - networking

    - name: Setup containers
      ansible.builtin.include_role:
        name: containers
      tags:
        - containers

