---
- name: Setup homelab
  hosts:
    - server

  tasks:
    - name: Setup filesystem (btrfs)
      ansible.builtin.include_role:
        name: filesystem
      tags:
        - filesystem

    - name: Install packages
      ansible.builtin.include_role:
        name: common
      tags:
        - common

    - name: Setup networking
      ansible.builtin.include_role:
        name: networking
      tags:
        - networking
